theme: jekyll-theme-slate
lang: ja-JP
title: '<a href="/ShellGeiData/" style="color:white">ã‚·ã‚§ãƒ«èŠ¸ã®æƒ…å ±ãƒšãƒ¼ã‚¸</a>'
description: ğŸ’©ğŸ’©ğŸ’©ğŸ’©ğŸ’©ğŸ’©ğŸ’©ğŸ’©ğŸ’©
markdown: kramdown
highlighter: rouge
